version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
      time: '00:00'
    open-pull-requests-limit: 5
    reviewers:
      - muhamedfazeel

  # Frontend (React/Vite - npm)
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
      time: '00:00'
    open-pull-requests-limit: 5
    reviewers:
      - muhamedfazeel

  # Python scripts (pip)
  - package-ecosystem: 'pip'
    directory: '/scripts'
    schedule:
      interval: 'weekly'
      time: '00:00'
    open-pull-requests-limit: 5
    reviewers:
      - muhamedfazeel
